### PR TITLE
Create Calci.B

### PR DESCRIPTION
**Pull request by bkrish1719205**
Bro I do this program which use of Console Application

### CODE REVIEW

**Review by swaroop325 — CHANGES_REQUESTED** [review]
Try in c and submit again

**Comment by bkrish1719205** [comment]
Why bro I will do in Console Application it is also a part of c na

**Comment by swaroop325** [comment]
I expected in pure c... thats why... if you face any problem msg me in whatsapp

**Comment by bkrish1719205** [comment]
Ok bro

**Pull request merged**
